/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mgalgs_bogus_example_hellojni_HellojniActivity */

#ifndef _Included_com_mgalgs_bogus_example_hellojni_HellojniActivity
#define _Included_com_mgalgs_bogus_example_hellojni_HellojniActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mgalgs_bogus_example_hellojni_HellojniActivity
 * Method:    getStrings
 * Signature: (Ljava/lang/String;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_mgalgs_bogus_example_hellojni_HellojniActivity_getStrings
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
